global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['time-server:8000']

  - job_name: aggregated-trace-metrics
    static_configs:
      - targets: ['otel-collector:8889']