services:
  jaeger-collector:
    ports:
      - "4444:4317"  # accept OpenTelemetry Protocol (OTLP) over gRPC
      - "4445:4318"  # accept OpenTelemetry Protocol (OTLP) over HTTP

  jaeger-query:
    ports:
      - "16686:16686"
      - "16687:16687"

  otel-collector:
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP http receiver
      - "8889:8889"  # Prometheus metrics exporter

  asp-app:
    ports:
      - 8005:8080

  server:
    ports:
      - 8000:8000

  app-b:
    ports:
      - "8001:8000"

  app-c:
    ports:
      - "8002:8000"
