services:
  server:
    build:
      context: ../../fastapi
    container_name: time-server
    environment:
      MODE: "otlp-grpc"
      OTEL_SERVICE_NAME: "app-a"
      OTLP_GRPC_ENDPOINT: "otel-collector:4317"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"
    depends_on:
      - otel-collector
    networks:
      - wesley_network

  app-b:
    build:
      context: ../../fastapi
    environment:
      MODE: "otlp-http"
      OTEL_SERVICE_NAME: "app-b"
      OTLP_HTTP_ENDPOINT: "http://otel-collector:4318/v1/traces"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"
    depends_on:
      - otel-collector
    networks:
      - wesley_network

  app-c:
    build: ../../fastapi
    environment:
      MODE: "otlp-grpc"
      OTEL_SERVICE_NAME: "app-c"
      OTLP_GRPC_ENDPOINT: "jaeger-collector:4317"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"
    depends_on:
      - otel-collector
    networks:
      - wesley_network