services:
  prometheus:
    image: prom/prometheus:v3.3.1
    container_name: prometheous
    volumes:
      - ../etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - otel-collector
      - jaeger-collector
    networks:
      - wesley_network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - wesley_network
volumes:
  grafana_data: