services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.57.0
    container_name: jaeger-collector
    command: 
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--collector.otlp.enabled=true"
    environment: 
      - SAMPLING_CONFIG_TYPE=adaptive
    restart: on-failure
    depends_on:
      - cassandra
      - cassandra-schema
    networks:
      - wesley_network

  jaeger-query:
    image: jaegertracing/jaeger-query:1.57.0
    container_name: jaeger-query
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
    restart: on-failure
    depends_on:
      - cassandra
      - cassandra-schema
      - jaeger-collector
    networks:
      - wesley_network

  cassandra:
    image: cassandra:4.1.4
    container_name: cassandra
    networks:
      - wesley_network

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.57.0
    depends_on:
      - cassandra
    networks:
      - wesley_network