services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0
    container_name: otel-collector
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ../etc/collector/otel-collector-config.yml:/conf/config.yaml
    restart: on-failure
    depends_on:
      - jaeger-collector
    networks:
      - wesley_network